const WORKER_NAME = 'WORKER_OPEN_API_INTEGRATE_GEN_CONTENT';
const JOB_NAME = 'GENERATE_CONTENT';

const DIFFICULTY = {
    EASY: 'EASY',
    MEDIUM: 'MEDIUM',
    HARD: 'HARD',
} as const;

export { WORKER_NAME, JOB_NAME, DIFFICULTY };
