version: '3.8'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    image: postgres:16-alpine
    container_name: dozu-postgres-dev
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - postgresql_16_dev_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - dozu-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgresql_16_dev_data:
    driver: local

networks:
  dozu-network:
    driver: bridge
